### ISSUE TITLE
Wrong warning message with an empty package name

### ISSUE THREAD

**Issue by kuroda** [kerl/kerl#245] opened 2017-11-13 09:18 UTC
I tried to build Erlang/OTP 19.3 with newly installed kerl, and got these messages:

```
$ kerl build 19.3 19.3
Verifying archive checksum...
Checksum verified (a8c259ec47bf84e77510673e1b76b6db)
Extracting source code
Building Erlang/OTP 19.3 (19.3), please wait...
WARNING: It appears that a required development package '' is not installed.
...
```

The warning message with an empty package name is meaningless.

**Comment by fredyouhanaie** [comment] 2017-11-20 18:45
I just had a look at the kerl script. The two functions `_check_dpkg()` and `_check_rpm()` each have a line `required=<<_...`. That construct will not work as intended, better to enclose the list of required packages in quotes.

In the present form, the list of packages to check is empty, hence the strange warning message.

Also, in the for loop below that assignment, the `"$required"` should not be quoted, otherwise the whole list will be checked as one item.

**Comment by mrallen1** [comment] 2018-01-23 17:39
Closing this issue since we merged #245

**Closed by mrallen1** 2018-01-23 17:39 UTC

**Comment by zhaohansprt** [comment] 2018-03-05 10:54
please make a release

**Comment by mrallen1** [comment] 2018-03-05 16:20
I didn't realize it'd been so long since we did one. I'll put it on the todo list today. Thanks for the reminder.

**Comment by mrallen1** [comment] 2018-03-05 22:39
Just tagged 1.8.2 Sorry for the delays in releases lately.
