### ISSUE TITLE
Activate non-zero exit code

### ISSUE THREAD

**Issue by jamhed** [kerl/kerl#238] opened 2017-10-23 23:18 UTC
activate script returns non-zero, therefore shell script with -e flag are failing on ` ~/activate` command.

**Comment by erszcz** [comment] 2017-11-07 14:55
`activate` should not be run (which starts a child shell), but sourced (which modifies the environment of the current shell):

```sh
. ~/activate
```

Instead of just:

```sh
~/activate
```

Are you sure you're doing the right thing in the script?

**Comment by jamhed** [comment] 2017-11-07 17:23
> Are you sure you're doing the right thing in the script?

Yes. This particular script fails:

#!/bin/sh -e
. ~/erlang/activate

This is a recent change, sometimes ago everything was fine.

**Comment by fenollp** [comment] 2017-11-14 00:17
Hey @jamhed, can it be that you have `set -o pipefail` somewhere? I know that got me: https://circleci.com/gh/fenollp/kerl/17

**Comment by monkeygroover** [comment] 2017-12-13 18:15
I'm seeing this too, updated recently and my direnv script is failing. pipefail is not set unless direnv is doing it under the hood.

**Comment by monkeygroover** [comment] 2017-12-13 18:49
And yes, latest kerl generated activate also causes our Jenkins script to fail which has a 'set -x'

**Comment by monkeygroover** [comment] 2017-12-13 19:58
I *think* it's caused by this line in activate

`kernel_history=$(echo "$ERL_AFLAGS" | grep "kernel shell_history")`

if i edit it to be `kernel_history=$(echo "$ERL_AFLAGS" | grep "kernel shell_history") || true` then it seems to stop it failing. I'll see if I can make a proper fix.

**Comment by monkeygroover** [comment] 2017-12-13 20:08
ah, looks like it is fixed, but not yet in a released version:

https://github.com/kerl/kerl/commit/78985ded0672d686c2868f13137eea7fdf5f7e10

**Comment by mrallen1** [comment] 2017-12-13 20:23
OK, thanks for the note - I'll try to spin up a release today or tomorrow.

**Comment by monkeygroover** [comment] 2017-12-13 20:25
ta

**Comment by jamhed** [comment] 2017-12-13 20:25
@monkeygroover great job :)

**Comment by mrallen1** [comment] 2018-01-23 17:40
I think this issue is resolved now, so I'm closing this issue. Please reopen if not.

**Closed by mrallen1** 2018-01-23 17:40 UTC
