### ISSUE TITLE
WARNING: It appears a required development package 'openssl-devel' is not installed.

### ISSUE THREAD

**Issue by nskalis** [kerl/kerl#365] opened 2021-03-05 20:56 UTC
Hi, 

in `openSUSE` linux distro, for example `15.2 (Leap)`  when trying to install `erlang`
`kerl` complains about `WARNING: It appears a required development package 'openssl-devel' is not installed.`
```
> kerl build 23.2.7 23.2.7
Extracting source code
Building Erlang/OTP 23.2.7 (23.2.7), please wait...
WARNING: It appears a required development package 'openssl-devel' is not installed.
APPLICATIONS DISABLED (See: /home/app/.kerl/builds/23.2.7/otp_build_23.2.7.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /home/app/.kerl/builds/23.2.7/otp_build_23.2.7.log)
 * wx             : Can not find C++ compiler
 * No OpenGL headers found, wx will NOT be usable
 * No GLU headers (glu.h) found, wx will NOT be usable
 * wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /home/app/.kerl/builds/23.2.7/otp_build_23.2.7.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.
 
 Erlang/OTP 23.2.7 (23.2.7) has been successfully built
```

The thing is that the package in question is named: `libopenssl-devel`

Is this something that you can address maybe?

**Comment by oshanz** [comment] 2021-07-15 13:35
clone of #323 ?

**Comment by paulo-ferraz-oliveira** [comment] 2024-01-08 22:06
Closing as duplicate of #323.

**Closed by paulo-ferraz-oliveira** 2024-01-08 22:06 UTC
